#!/bin/sh
#
# Copyright (c) 2025  Vladimir Makarov <vmakarov@gcc.gnu.org>
#
# Usage: compare.sh
#
# The script uses Bison, Yacc (byacc), gcc, lex, YAEP.
#

SRCDIR=`dirname $0`

YACC=
if type yacc|grep -F /yacc; then
    YACC=yacc
elif type byacc|grep -F /byacc; then
    YACC=byacc;
fi
BISON=
if type bison|grep -F /bison; then
    BISON=bison
fi
MSTA=
if test -f ./msta; then
    MSTA=./msta
fi

GCC='gcc -O3 -w -DNDEBUG'
TEST=small_test.i
BIG_TEST=$SRCDIR/whole_gcc_test.i
outfile=./a.out

echo This script compares speed of parser generated by Yacc, Bison, Msta, YAEP
echo for parsing real C program.

echo Now test file preparation

cp $SRCDIR/test.i $TEST
for i in 0 1 2 3 4 5 6 7 8 9;do cat $SRCDIR/test1.i >>$TEST;done

if test x$BISON != x; then
  # BISON
  echo ++++++++Bison: pure parsing
  if $BISON -y $SRCDIR/ansic.y && $GCC -I$SRCDIR -I$SRCDIR/.. $SRCDIR/test_yyparse.c -o $outfile && time $outfile <$TEST; then
    echo
  else
    echo Failure with $BISON
    exit 1
  fi
fi

if test x$BISON != x; then
  # BISON
  echo Bison -- Big test "(lines: `wc -l $BIG_TEST`)"
  if $BISON -y $SRCDIR/ansic.y && $GCC -I$SRCDIR -I$SRCDIR/.. $SRCDIR/test_yyparse.c -o $outfile && time $outfile <$BIG_TEST; then
    echo
  else
    echo Failure with $BISON on the big test
    exit 1
  fi
fi

if test x$YACC != x; then
  # YACC
  echo ++++++++Yacc: pure parsing
  if $YACC -y $SRCDIR/ansic.y && $GCC -I$SRCDIR -I$SRCDIR/.. $SRCDIR/test_yyparse.c -o $outfile && time $outfile <$TEST; then
    echo
  else
    echo Failure with $YACC
    exit 1
  fi
fi

if test x$YACC != x; then
  # YACC
  echo YACC -- Big test "(lines: `wc -l $BIG_TEST`)"
   
  if $YACC -y $SRCDIR/ansic.y && $GCC -I$SRCDIR -I$SRCDIR/.. $SRCDIR/test_yyparse.c -o $outfile && time $outfile <$BIG_TEST; then
    echo
  else
    echo Failure with $YACC on the big test
    exit 1
  fi
fi

if test x$MSTA != x; then
    # MSTA
    echo ++++++++Msta: pure parsing
    if $MSTA -yacc-file-names -y $SRCDIR/ansic.y && $GCC -I$SRCDIR -I$SRCDIR/.. $SRCDIR/test_yyparse.c -o $outfile && time $outfile <$TEST; then
	echo
    else
	echo Failure with $MSTA
	exit 1
    fi
fi

if test x$MSTA != x; then
    # MSTA
    echo Msta -- Big test "(lines: `wc -l $BIG_TEST`)"
    if $MSTA -yacc-file-names -y $SRCDIR/ansic.y && $GCC -I$SRCDIR -I$SRCDIR/.. $SRCDIR/test_yyparse.c -o $outfile && time $outfile <$BIG_TEST; then
	echo
    else
	echo Failure with $MSTA on the big test
	exit 1
    fi
fi

YAEPDIR=
if test -f /usr/local/include/yaep/yaep.h; then
    YAEPDIR=/usr/local/include/yaep
elif test -f /usr/include/yaep/yaep.h; then
    YAEPDIR=/usr/include/yaep
elif test -f /usr/local/include/yaep.h; then
    YAEPDIR=/usr/local/include/yaep.h
elif test -f /usr/include/yaep.h; then
    YAEPDIR=/usr/include/yaep.h
fi

YAEPLIB=
if test -f /usr/local/lib/libyaep.a; then
    YAEPLIB=/usr/local/lib/libyaep.a
elif test -f /usr/lib/libyaep.a; then
    YAEPLIB=/usr/lib/libyaep.a
elif test -f /usr/include/yaep.h; then
    YAEPDIR=
fi

if test x$YAEPDIR != x; then

    YAEPDIR=/usr/local/include/yaep
    YAEPLIB=/usr/local/lib/libyaep.a

    # YAEP (Yet Another Earley Parser)
    echo ++++++++YAEP '(Yet Another Earley Parser)': pure parsing
    echo Static Lookahead
    if $GCC -DYAEP -I$YAEPDIR -I$SRCDIR/.. -I$SRCDIR $SRCDIR/test_gp.c $YAEPLIB -o $outfile && time $outfile 1 0 <$TEST; then
	echo
    else
	echo Failure with 'YAEP (Yet Another Earley Parser)'
	exit 1
    fi
    
    echo Static Lookahead -- Big test "(lines: `wc -l $BIG_TEST`)"
    if $GCC -DYAEP -I$YAEPDIR -I$SRCDIR/.. -I$SRCDIR $SRCDIR/test_gp.c $YAEPLIB -o $outfile && time $outfile 1 1 <$BIG_TEST; then
	echo
    else
	echo Failure with 'YAEP (Yet Another Earley Parser)'
	exit 1
    fi
    echo ++++++++YAEP: ambiguous 'E=E+E|a' and 300 operators
    if $GCC -DYAEP -I$YAEPDIR -I$SRCDIR/.. -I$SRCDIR $SRCDIR/ambig.c $YAEPLIB -o $outfile && time $outfile 1; then
	echo
    else
	echo Failure with 'GP (General Parser)'
	exit 1
    fi

fi

# GP 
echo ++++++++GP: pure parsing
if $GCC -I$SRCDIR/.. -I$SRCDIR $SRCDIR/test_gp.c $SRCDIR/../gparser.c -o $outfile && time $outfile 1 <$TEST; then
  echo
else
  echo Failure with 'GP (General Parser)'
  exit 1
fi

echo GP -- Big test "(lines: `wc -l $BIG_TEST`)"
if $GCC -I$SRCDIR/.. -I$SRCDIR $SRCDIR/test_gp.c $SRCDIR/../gparser.c -o $outfile && time $outfile 1 <$BIG_TEST; then
  echo
else
  echo Failure with 'GP (General Parser)'
  exit 1
fi

echo ++++++++GP: ambiguous 'E=E+E|a' and 300 operators
if $GCC -I$SRCDIR/.. -I$SRCDIR $SRCDIR/ambig.c $SRCDIR/../gparser.c -o $outfile && time $outfile 1; then
  echo
else
  echo Failure with 'GP (General Parser)'
  exit 1
fi

rm -f $outfile
rm -f y.tab.c $TEST
exit 0
